#!/bin/bash
#
# Perform necessary cloudkeeper-one removal steps
# after package is uninstalled.
#

PROGNAME=$(basename $0)
INSTALLER_DIR=`dirname $0`

SYSD_DIR="/etc/systemd/system"
BIN_DIR="/usr/bin"

DEST_DIR="/opt/cloudkeeper-one"
CONFIG_DIR="/etc/cloudkeeper-one"
LOG_DIR="/var/log/cloudkeeper-one"
SPOOL_DIR="/var/spool/cloudkeeper-one"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

function remdir
{
  if [ -d "$1" ]; then
    rm -rf "$1" || error_exit "Could not unlink $1"
  fi
}

if [ "X$1" = "Xpurge" ] || [ "X$1" = "X0" ]; then
  # clean up systemd integration
  for SD_FILE in ${SYSD_DIR}/cloudkeeper-one.* ; do
    rm "$SD_FILE" || error_exit "Could not unlink $SD_FILE"
  done

  # clean up links
  if [ -L "$BIN_DIR/cloudkeeper-one" ]; then
    rm "$BIN_DIR/cloudkeeper-one"
  fi

  # clean up runtime directories
  remdir "$DEST_DIR"
  remdir "$CONFIG_DIR"
  remdir "$LOG_DIR"
  remdir "$SPOOL_DIR"
fi

echo "cloudkeeper-one has been uninstalled!"

exit 0
