#!/bin/bash
#
# Perform necessary cloudkeeper-one setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# stop cloudkeeper-one GRPC service
service cloudkeeper-one stop

exit 0
